version: '3'
services:
  frontend:
    image: covid19-rader-for-japan/frontend:latest
    depends_on: 
        - backend
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - mynet

  backend:
    image: covid19-rader-for-japan/backend:latest
    depends_on: 
      - backend-calculator
    ports:
      - "0.0.0.0:5000:5000"
    networks:
      - mynet

networks:
  mynet:
    external: true