import uuid from 'uuid/v1';
import { MarketType, TradeType, Item, Statistics } from '../../../types';
import moment from 'moment';

export const items = <Item[]>[
	{
		ID: uuid(),
		MarketType: MarketType.FX,
		StartDate: moment([2019, 10, 10]).toISOString(),
		EndDate: moment([2019, 10, 10]).toISOString(),
		TradeType: TradeType.BUY,
		Pair: "USD/JPY",
		Lot: 2.0,
		EntryRate: 1.0,
		LossCutRate: 1.0,
		SettleRate: 1.0,
		Profit: 1.0,
		BeforeComment: "good",
		AfterComment: "good",
		Tags: [],
		Images: [],
		UpdatedAt: moment([2019, 10, 10]).toISOString(),
		CreatedAt: moment([2019, 10, 10]).toISOString()
	},
	{
		ID: uuid(),
		MarketType: MarketType.FX,
		StartDate: moment([2019, 10, 10]).toISOString(),
		EndDate: moment([2019, 10, 10]).toISOString(),
		TradeType: TradeType.BUY,
		Pair: "USD/JPY",
		Lot: 2.0,
		EntryRate: 1.0,
		LossCutRate: 1.0,
		SettleRate: 1.0,
		Profit: 1.0,
		BeforeComment: "good",
		AfterComment: "good",
		Tags: [],
		Images: [],
		UpdatedAt: moment([2019, 10, 10]).toISOString(),
		CreatedAt: moment([2019, 10, 10]).toISOString()
	},
	{
		ID: uuid(),
		MarketType: MarketType.FX,
		StartDate: moment([2019, 11, 10]).toISOString(),
		EndDate: moment([2019, 11, 10]).toISOString(),
		TradeType: TradeType.BUY,
		Pair: "USD/JPY",
		Lot: 2.0,
		EntryRate: 1.0,
		LossCutRate: 1.0,
		SettleRate: 1.0,
		Profit: 1.0,
		BeforeComment: "good",
		AfterComment: "good",
		Tags: [],
		Images: [],
		UpdatedAt: moment([2019, 11, 10]).toISOString(),
		CreatedAt: moment([2019, 11, 10]).toISOString()
	},
	{
		ID: uuid(),
		MarketType: MarketType.FX,
		StartDate: moment([2019, 4, 10]).toISOString(),
		EndDate: moment([2019, 4, 10]).toISOString(),
		TradeType: TradeType.BUY,
		Pair: "USD/JPY",
		Lot: 2.0,
		EntryRate: 1.0,
		LossCutRate: 1.0,
		SettleRate: 1.0,
		Profit: 1.0,
		BeforeComment: "good",
		AfterComment: "good",
		Tags: [],
		Images: [],
		UpdatedAt: moment([2019, 4, 10]).toISOString(),
		CreatedAt: moment([2019, 4, 10]).toISOString()
	}
];

export const novemberItems = <Item[]>[
	{
		ID: uuid(),
		MarketType: MarketType.FX,
		StartDate: moment([2019, 10, 10]).toISOString(),
		EndDate: moment([2019, 10, 10]).toISOString(),
		TradeType: TradeType.BUY,
		Pair: "USD/JPY",
		Lot: 2.0,
		EntryRate: 1.0,
		LossCutRate: 1.0,
		SettleRate: 1.0,
		Profit: 1.0,
		BeforeComment: "good",
		AfterComment: "good",
		Tags: [],
		Images: [],
		UpdatedAt: moment([2019, 10, 10]).toISOString(),
		CreatedAt: moment([2019, 10, 10]).toISOString()
	},
	{
		ID: uuid(),
		MarketType: MarketType.FX,
		StartDate: moment([2019, 10, 10]).toISOString(),
		EndDate: moment([2019, 10, 10]).toISOString(),
		TradeType: TradeType.BUY,
		Pair: "USD/JPY",
		Lot: 2.0,
		EntryRate: 1.0,
		LossCutRate: 1.0,
		SettleRate: 1.0,
		Profit: 1.0,
		BeforeComment: "good",
		AfterComment: "good",
		Tags: [],
		Images: [],
		UpdatedAt: moment([2019, 10, 10]).toISOString(),
		CreatedAt: moment([2019, 10, 10]).toISOString()
	},
];

export const novemberStatistics = <Statistics>{
	InitialInvestment: 0,
	ProfitBefore: 1,
	TotalAssets: 3,
	NumDepWith: 0,
	AmountDepWith: 0,
	TotalProfitAndLoss: 2,
	TotalProfit: 2,
	TotalLoss: 0,
	WinRate: 100,
	NumTrade: 2,
	NumWin: 2,
	NumLose: 0,
	ProfitRatio: Infinity,
	ProfitAve: 1,
	LossAve: 0,
}
