export { default as Budget } from './Asset';
export { default as LatestOrders } from './LatestOrders';
export { default as LatestProducts } from './LatestProducts';
export { default as LatestCalendar } from './LatestCalendar';
export { default as LatestProfit } from './LatestProfit';
export { default as TasksProgress } from './TasksProgress';
export { default as TotalProfit } from './TotalProfit';
export { default as TotalUsers } from './ProfitRatio';
export { default as UsersByDevice } from './TradesByPair';
